close all;
clear;
clc;
%% load nc data
input_data_path = '/Users/phoenix/Google_Drive/Tsinghua_Luo/Projects/DATAHUB/TRENDY_CLM5/input_data/';
output_data_path = '/Users/phoenix/Google_Drive/Tsinghua_Luo/Projects/DATAHUB/TRENDY_CLM5/output_data/';
fig_data_path = '/Users/phoenix/Google_Drive/Tsinghua_Luo/Projects/DATAHUB/TRENDY_CLM5/figures/';

% input_data_path = '/glade/p/cgd/tss/people/dll/TRENDY2020_History/S0/';
% output_data_path = '/glade/scratch/taofeng/trendy_clm5/output_data/';
% fig_data_path = '/glade/scratch/taofeng/trendy_clm5/output_data/figures/';

scenario_name = 'S3_CO2ClimateLUC_Matrix'; % 'S0_constant', 'S3_CO2ClimateLUC', S3_CO2ClimateLUC_Matrix
% grid info
lon_size = 288;
lat_size = 192;
depth_size = 20;
time_size = 3840;

% load grid info
load([output_data_path, 'sample_grid_info.mat']);
%% processing
var_name_list = {
    'SOIL3C_vr', 'GPP', 'SCALAR_T'...
    };

% var_name_list = {'ALTMAX', ...
% 		'GPP', 'NPP', 'NEP', ...
% 		'HR', 'HR_vr', ...
% 		'CWDC', 'CWDC_vr', ...
% 		'LITR1C', 'LITR1C_vr', ...
% 		'LITR2C', 'LITR2C_vr', ...
% 		'LITR3C', 'LITR3C_vr', ...
% 		'O_SCALAR', 'T_SCALAR', 'W_SCALAR', 'FPI', ...
% 		'SOIL1C', 'SOIL1C_vr', ...
% 		'SOIL2C', 'SOIL2C_vr', ...
% 		'SOIL3C', 'SOIL3C_vr', ...
% 		'SOILC_vr', ...
% 		'SOILC_HR', ...
% 		'TOTLITC', ...
% 		'TOTSOMC', ...
% 		};


% var_name_list = {'ALTMAX', ...
% 		'GPP', 'NPP', 'NEP', ...
% 		'HR', 'HR_vr', ...
% 		'CWDC', 'CWDC_vr', 'CWDC_Cap_vr', ...
% 		'LITR1C', 'LITR1C_vr', 'LITR1C_Cap_vr', ...
% 		'LITR2C', 'LITR2C_vr', 'LITR2C_Cap_vr', ...
% 		'LITR3C', 'LITR3C_vr', 'LITR3C_Cap_vr', ...
% 		'O_SCALAR', 'T_SCALAR', 'W_SCALAR', 'FPI', ...
% 		'SOIL1C', 'SOIL1C_vr', 'SOIL1C_Cap_vr', ...
% 		'SOIL2C', 'SOIL2C_vr', 'SOIL2C_Cap_vr', ...
% 		'SOIL3C', 'SOIL3C_vr', 'SOIL3C_Cap_vr', ...
% 		'SOILC_vr', ...
% 		'TOTLITC', ...
% 		'TOTSOMC', ...
% 		};

% land mask
land_area = ncread([input_data_path, 'TRENDY2020_', scenario_name, '.clm2.h0.GPP.170001-201912.nc'], 'area'); % units = "km^2"
land_area = land_area*10^6;  % units = "m^2"
save([output_data_path, 'global_trendy2020_clm5_land_area.mat'], 'land_area');
land_area = repmat(land_area, [1, 1, time_size]);

for ivar = 1:length(var_name_list)
    % basic info of variables
    var_name = var_name_list{ivar};
    nc_var_info = ncinfo([input_data_path, 'TRENDY2020_', scenario_name, '.clm2.h0.', var_name, '.170001-201912.nc'], var_name);
    var_dimension = length(nc_var_info.Size);
    disp(struct2table(nc_var_info.Attributes))
    
    if var_dimension == 3
        disp([datestr(now,'HH:MM:SS'), ' processing var ', var_name]);
        
        var_data_origin = ncread([input_data_path, 'TRENDY2020_', scenario_name, '.clm2.h0.', var_name, '.170001-201912.nc'], var_name);
        area_weighted_sum = reshape(sum(var_data_origin.*land_area, [1, 2], 'omitnan'), [time_size, 1]);
        
    elseif var_dimension == 4
        area_weighted_sum = nan(time_size, depth_size);
        for idepth = 1:depth_size
            disp([datestr(now,'HH:MM:SS'), ' processing var ', var_name, ' depth ', num2str(idepth)]);
            
            var_data_origin = ncread([input_data_path, 'TRENDY2020_', scenario_name, '.clm2.h0.', var_name, '.170001-201912.nc'],...
                var_name, [1, 1, idepth, 1], [lon_size, lat_size, 1, time_size], [1, 1, 1, 1]);
            var_data_origin = reshape(var_data_origin(:, :, 1, :), [lon_size, lat_size, time_size]);
            area_weighted_sum_middle = reshape(sum(var_data_origin.*land_area, [1, 2], 'omitnan'), [time_size, 1]);
            area_weighted_sum(:, idepth) = area_weighted_sum_middle;
            
        end
    end
    save([output_data_path, 'global_trendy2020_clm5_', scenario_name, '_', var_name, '_170001_201912.mat'], 'area_weighted_sum');
    
end

disp('end of programme')

